derdubor:
    url: /derdubor/
    title: Der du bor
    pages:
        - 
            id: akershus
            url: /akershus/
            title: Akershus
        - 
            id: aust-agder
            url: /aust-agder/
            title: Aust-Agder
        - 
            id: buskerud
            url: /buskerud/
            title: Buskerud
        - 
            id: finnmark
            url: /finnmark/
            title: Finnmark
        - 
            id: hedmark
            url: /hedmark/
            title: Hedmark
        - 
            id: hordaland
            url: /hordaland/
            title: Hordaland
        - 
            id: moreogromsdal
            url: /moregoromsdal/
            title: Møre og Romsdal
        - 
            id: nordtrondelag
            url: /nord-trondelag/
            title: Nord-Trøndelag
        - 
            id: nordland
            url: /nordland/
            title: Nordland
        - 
            id: oslo
            url: /oslo/
            title: Oslo
        - 
            id: rogaland
            url: /rogaland/
            title: Rogaland
        - 
            id: sognogfjordane
            url: /sognogfjordane/
            title: Sogn og Fjordane
        - 
            id: sortrondelag
            url: /sor-trondelag/
            title: Sør-Trøndelag
        - 
            id: telemark
            url: /telemark/
            title: Telemark
        - 
            id: troms
            url: /troms/
            title: Troms
        - 
            id: vestagder
            url: /vest-agder/
            title: Vest-Agder
        - 
            id: vestfold
            url: /vestfold/
            title: Vestfold
        - 
            id: ostfold
            url: /ostfold/
            title: Østfold


UKM:
    url: /
    title: UKM
    #color: d4c8e4
    pages:
        - 
            id: forsiden
            url: /
            title: Forsiden
            description: Ung kultur møtes
        - 
            id: hvaer
            url: /hva-er/
            title: Hva er UKM?
            description: Alt om Ung Kultur Møtes
        - 
            id: hvameldepa
            url: /hva-kan-jeg-delta-med/
            title: Hva kan du delta med?
            description: 
        - 
            id: ua
            url: /unge-arrangører/
            title: Unge arrangører
            description: 
        - 
            id: ambassadorer
            url: //ambassador.ukm.no/
            title: Ambassadører
            description: Bli kjent med oss
        - 
            id: urg
            url: /urg/
            title: URG (ung ressursgruppe)
            description: 
        - 
            id: ukmere
            url: /ukmere/
            title: Kjente UKMere
            description: 


ukmtv:
    url: //tv.ukm.no
    title: UKM-TV
    pages:
        -
            id: tvsok
            url: //tv.ukm.no/search/
            title: Søk
        -
            id: festivaltv
            url: //tv.ukm.no/festivalen/
            title: UKM-festivalen
        -
            id: fylketv
            url: //tv.ukm.no/fylke/
            title: Fylkesfestivalene
        -
            id: tvsok
            url: //tv.ukm.no/lokal/
            title: Lokalarrangementene
            


            
egoego:
    url: //egoego.no
    title: Ego
    pages:
        - 
            id: egoforsiden
            url: //egoego.no
            title: Forsiden
            description:
        - 
            id: egoom
            url: //egoego.no/om-oss/
            title: Hva er ego?
            description:
        -
            id: egokontakt
            url: //egoego.no/kontakt
            title: Kontakt oss
            
            
organisasjonen:
    url: //om.ukm.no/
    title: Organisasjonen
    pages:
        - 
            id: forsiden
            url: /om.ukm.no/
            title: Nyheter
        - 
            id: presse
            url: //pressemelding.ukm.no
            title: Alt til din avis (for journalister)
        - 
            id: pressebilder
            url: //www.flickr.com/photos/ukm/albums
            title: Pressebilder
        - 
            id: grafikk
            url: /om.ukm.no/
            title: Grafisk profil
        - 
            id: kontakt
            url: /om.ukm.no/kontakt/
            title: Kontakt oss
        - 
            id: bakgrunn
            url: /om.ukm.no/verdier/
            title: Verdier
        - 
            id: historikk
            url: /om.ukm.no/historikk/
            title: Historikk
        - 
            id: tidligerear
            url: /tidligere-ar/
            title: UKM fra 2001 i dag
            description: Bli kjent med oss

        - 
            id: login
            url: //ukm.no/wp-admin/
            title: Logg inn for arrangører
            description: 
            
english:
    url: //om.ukm.no/english
    title: English
    pages:
        - 
            id: about
            url: //om.ukm.no/about/
            title: About UKM
